# Generated by Django 5.2.4 on 2025-10-28 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginToken',
        ),
        migrations.AddField(
            model_name='coustomeruser',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coustomeruser',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
