# Generated by Django 5.2.4 on 2025-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_delete_logintoken_coustomeruser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('token', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coustomeruser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coustomeruser',
            name='isActive',
        ),
    ]
