# Generated by Django 5.2.4 on 2025-12-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_age', models.IntegerField()),
                ('emp_location', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(max_length=100)),
            ],
        ),
    ]
